platform :ios, '8.0'

target 'KYDrawProject' do
  pod 'MJRefresh', '3.1.12'
  pod 'AFNetworking', '3.1.0'
  pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
  pod 'Qiniu', '7.1'
  pod 'Wilddog', '2.3.0'
  pod 'Toast', '3.1.0'
  pod 'Masonry', '1.0.2'
  pod 'NSDate+Calendar', '0.0.9'
  pod 'TTTAttributedLabel', '1.13.4'
  pod 'JPush', '3.0.2'
  pod 'GrowingIO'
  pod 'MLeaksFinder'
  pod 'ReactiveObjC','3.0.0'
#  pod 'Pingpp/Alipay', '~> 2.2.10'
#  pod 'Pingpp/Wx', '~> 2.2.10'
  pod 'IQKeyboardManager','4.0.8'
  pod 'MJExtension','3.0.13'
  pod 'SDWebImage'
end
